name: run-tests
on: [push]
jobs:
  run-tests:
    runs-on: ubuntu-latest
    container:
      image: docker.io/mihail911/fake-news:v1
      credentials:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_PAT }}
    steps:
      - name: Set env variables
        run: echo "PYTHONPATH=$PYTHONPATH:/home/fake-news" >> $GITHUB_ENV
      - name: Change working directory
        run: cd "/home/fake-news"
      - name: Echo vars
        run: echo "$PYTHONPATH"
      - name: Run unit tests
        working-directory: ../
        run: pytest tests/
