name: run-tests
on: [push]
jobs:
  run-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install Python 3
        uses: actions/setup-python@v1
        with:
          python-version: 3.8
      - name: Install dependencies
        run: pip install -r requirements.txt
      - name: Set env variables
        run: export PYTHONPATH=$PYTHONPATH:`pwd`
      - name: Show env variables
        run: echo $PYTHONPATH
      - name: Run unit tests
        run: pytest tests/
