name: run-tests
on: [push]
defaults:
  run:
    working-directory: /home/fake-news
jobs:
  run-tests:
    runs-on: ubuntu-latest
    container:
      image: docker.io/mihail911/fake-news:v1
      credentials:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_PAT }}
    steps:
      - name: Set env variables
        run: echo "PYTHONPATH=$PYTHONPATH:/home/fake-news" >> $GITHUB_ENV
      - name: Change working directory
        run: cd /home/fake-news
      - name: Echo vars
        run: echo "$PYTHONPATH"
      - name: ls vars
        run: ls /__w/
      - name: ls stuff
        run: ls
      - name: Run unit tests
        run: pytest tests/
