name: run-tests
on: [push]
jobs:
  run-tests:
    runs-on: ubuntu-latest
    container:
      image: docker.io/mihail911/fake-news:v1
      credentials:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_PAT }}
    steps:
      - name: Set env variables
        run: echo "PYTHONPATH=$PYTHONPATH:`pwd`" >> $GITHUB_ENV
      - name: Run unit tests
        run: pytest tests/
